# SSGMinetopiaAddons by jerskisnow
# Version 2.0.0

# Dit komt in de chat te staan als een speler geen toegang heeft tot een command!
NoPermissions: '&cJij hebt hier geen toegang voor!'

Texturepack: '&3Hier kan je jouw texurepack link plakken!'

# ---=[Nightvision]=---
NightVisionOff: '&9Nightvision mode is uitgeschakeld!'
NightVisionOn: '&9Nightvision mode is ingeschakeld!'

# ---=[Antibreak/Antiplace]=---
NoBreak_Enabled: true
NoPlace_Enabled: true
NoBreakMessage: '&cJe hebt geen toegang om blokken te breken!'
NoPlaceMessage: '&cJe hebt geen toegang om blokken te plaatsen!'

# ---=[Armorkleur veranderen]=---
KleurSuccesvol: '&cJe hebt het item de kleur #<hexcode> gegeven!'
FouteArgumenten: '&cJe moet geldige argumenten invullen!'
GeenArmorInHand: '&cJe moet leather armor in je hand houden!'