# SSGMinetopia Addons plugin by jerskisnow

# Dit komt in de chat te staan als een speler geen toegang heeft tot een command!
NoPermissions: 'Jij hebt hier geen toegang voor!'

texturepack: '&3Hier kan je jouw texurepack link plakken!'

# ---=[Nightvision]=---
NightVisionOff: '&9Nightvision mode is uitgeschakeld!'
NightVisionOn: '&9Nightvision mode is ingeschakeld!'

# ---=[Antibreak/Antiplace]=---
NoBreakMessage: '&cYou are not permitted to break that block!'
NoPlaceMessage: '&cYou are not permitted to place that block!'

# ---=[Armorkleur veranderen]=---
KleurSuccesvol: '&cJe hebt het item de kleur #<hexcode> gegeven!'
FouteArgumenten: '&cJe moet geldige argumenten invullen!'
GeenArmorInHand: '&cJe moet leather armor in je hand houden!'
