name: SSGMinetopiaAddons
version: 1.0
main: nl.jerskisnow.ssgminetopiaaddons.Main
description: SSGMinetopiaAddons by jerskisnow

commands:
  texturepack:
    usage: /<command>
    aliases: [resourcepack]
    description: Texturepack Command!
  nightvision:
    usage: /<command>
    aliases: [nv]
    description: Nightvision Command!
  rename:
    usage: /<command>
    description: Rename Command!
  setlore:
    usage: /<command>
    description: Setlore Command!
  armorkleur:
    usage: /<command>
    description: ArmorKleur Command!
  aangifte:
    usage: /<command>
    description: Aangifte Command!
  huiszoekingsbevel:
    usage: /<command>
    description: Huiszoekingsbevel Command!

permissions:
    ssgminetopia.admin:
        description: Use this permissions for the admin commands!
        default: op
    ssgminetopia.build:
        description: Use this permissions to break and place blocks!
        default: op
    ssgminetopia.nightvision:
        description: Use this permissions to toggle nightvision mode!
    ssgminetopia.huiszoekingsbevel:
        description: Use this permissions to toggle nightvision mode!
default: op