name: SSGMinetopiaAddons
version: 2.0.0
main: nl.jerskisnow.ssgminetopiaaddons.Main
description: SSGMinetopiaAddons by jerskisnow

commands:
  texturepack:
    usage: /<command>
    aliases: [resourcepack]
    description: Texturepack Command!
  nightvision:
    usage: /<command>
    aliases: [nv]
    description: Nightvision Command!
  rename:
    usage: /<command>
    description: Rename Command!
  setlore:
    usage: /<command>
    description: Setlore Command!
  armorkleur:
    usage: /<command>
    description: ArmorKleur Command!
  aangifte:
    usage: /<command>
    description: Aangifte Command!
  huiszoekingsbevel:
    usage: /<command>
    description: Huiszoekingsbevel Command!
  leningsbewijs:
    usage: /<command>
    description: Leningsbewijs Command!

permissions:
    ssgminetopia.admin:
        description: Dit is de permission voor de admin commands!
        default: op
    ssgminetopia.build:
        description: Dit is de permission om blokken te plaatsen en te breken!
        default: op
    ssgminetopia.nightvision:
        description: Dit is de permission om nightvision aan en uit te zetten!
        default: op
    ssgminetopia.politie:
        description: Dit is de permission voor de politie commands!
        default: op
    ssgminetopia.bank:
        description: Dit is de permission voor de politie commands!
        default: op